apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: monitoring
type: Opaque
data:
  # Replace this with your base64 encoded GitHub token
  # Example: echo -n "your-token" | base64
  GITHUB_TOKEN: "YOUR_BASE64_ENCODED_TOKEN"
